### ISSUE TITLE
Cache files are not being removed in current pub release

### ISSUE THREAD

**Issue by js2702** [Baseflow/flutter_cache_manager#476]
## 🐛 Bug Report

The recent bug fix in the commit #469 does actually fix a serious bug which has been in the library for two years where the cache files are neved cleaned up because the `file.exists()` doesn't point to the correct file. The fix has been merged but the release in pub.dev is missing.

There are several issues about this behaviour that have been reported for quite some time.

#377, #452, #446 

@mvanbeusekom Sorry for the ping but I believe this is a serious fix missing.

**Comment by escamoteur** [comment]
Could you please push a new release? Our users reported cache sized of 30GB in some cases

**Comment by suli1** [comment]
Any update ?

**Comment by mikefaust-jm** [comment]
For the time being pin the version in your pubspec.yaml to the current git commit:
```yaml
  flutter_cache_manager:
    git:
      url: https://github.com/Baseflow/flutter_cache_manager.git
      path: flutter_cache_manager
      ref: "54904e4"
```

**Comment by gokturkDev** [comment]
This is a super important issue please take a look at it @mvanbeusekom

**Comment by gokturkDev** [comment]
Is this library abandoned @mvanbeusekom? Please mark it as archive-only or consider transferring the ownership as its dependant on so many people

**Comment by ChiaraMC** [comment]
> For the time being pin the version in your pubspec.yaml to the current git commit:
> 
>   flutter_cache_manager:
>     git:
>       url: https://github.com/Baseflow/flutter_cache_manager.git
>       path: flutter_cache_manager
>       ref: "54904e4"

This is still not working for me by the way, the files are not deleted after `stalePeriod` has passed. I'm testing by setting it to a minute, not sure if there's some kind of lower limit on it

**Comment by kirstenkoa** [comment]
Also interested in seeing this issue resolved. Can a new version be published with the fix? 

Pointing to the specific commit doesn't seem to play nicely with cached_network_image

Thanks!

**Comment by HeftyCoder** [comment]
This library is downloaded by a lot of developers each day/month. At the very least, this should be fixed. It's almost 1 year since this has been pushed, but a new version hasn't been released and we're left with applications which take continuously growing space.

**Comment by Taharu** [comment]
any update?

**Comment by gokturkDev** [comment]
500k weekly downloads for a cache manager that doesnt ... cache 😬

**Comment by ThunderFollower** [comment]
Bro, we need this fix to be published on pub.dev

**Comment by VinsonGuo** [comment]
I checked the code and found that this bug had been fixed on the dev branch, but it still exists on the main branch and pub.dev. This issue affected almost all Flutter apps. I can't believe how much useless cache space every Flutter app wasted.
